sudo: false
language: node_js
node_js:
  - "node"
before_install:
  - npm i -g npm
script:
  - npm i
  - npm run bootstrap
  - npm run lint
  - npm run test-ci
  - npm run build
cache:
  directories:
    - node_modules/
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  fqdn: reactackle-docs.braincrumbs.io
  on:
    branch: master
